afk-messages:
  titles:
    - '&#458a43잠수중...'
  subtitles:
    - '&#79bd77잠수포인트를 획득중입니다.'

return-messages:
  titles:
    - '&#458a43잠수 해제'
  subtitles:
    - '&#79bd77어서오세요!'

#AFK돌입 이벤트
afk-effect:
  enabled: true
  effect: 'BLINDNESS'
#AFK돌입 사운드
afk-sounds:
  enabled: true
  afk: 'UI_CARTOGRAPHY_TABLE_TAKE_RESULT'
  return: 'UI_LOOM_SELECT_PATTERN'

# %AFKpoint_Point% - 플레이어 포인트 변수 입니다.
